default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tweets_development

test:
  <<: *default
  database: tweets_test


production:
  <<: *default
  database: tweets_production
  username: tweets
  password: <%= ENV['TWEETS_DATABASE_PASSWORD'] %>
